// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVEji_wB-BmcWT44d5CjCxPAqZ1w-cXrE',
    appId: '1:92417457302:web:a0e0bcac86fc6b9f1456b7',
    messagingSenderId: '92417457302',
    projectId: 'chat-app-65f8a',
    authDomain: 'chat-app-65f8a.firebaseapp.com',
    storageBucket: 'chat-app-65f8a.appspot.com',
    measurementId: 'G-BV5CD4Y8BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbP_VIOdv5b-Yb8o2ZDyQKZMuxkKGQUEE',
    appId: '1:92417457302:android:08942f084be3a6121456b7',
    messagingSenderId: '92417457302',
    projectId: 'chat-app-65f8a',
    storageBucket: 'chat-app-65f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvwOwmWZjDRGDpJsgBg-ACwUSYvtXbyuE',
    appId: '1:92417457302:ios:3db7c473927411b51456b7',
    messagingSenderId: '92417457302',
    projectId: 'chat-app-65f8a',
    storageBucket: 'chat-app-65f8a.appspot.com',
    iosClientId: '92417457302-90luj4aj17eoammrs8cnua2k2cl69km1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvwOwmWZjDRGDpJsgBg-ACwUSYvtXbyuE',
    appId: '1:92417457302:ios:3db7c473927411b51456b7',
    messagingSenderId: '92417457302',
    projectId: 'chat-app-65f8a',
    storageBucket: 'chat-app-65f8a.appspot.com',
    iosClientId: '92417457302-90luj4aj17eoammrs8cnua2k2cl69km1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
